import unidecode

archetype_names = [
    "Balafré enragé",
    "Barbare sauvage",
    "Barbare urbain",
    "Briseur de titan",
    "Brute avinée",
    "Carcasse métallique",
    "Concasseur",
    "Enragé haineux",
    "Frère élémentaire",
    "Furie montée",
    "Guerrier totem",
    "Invulnérable enragé",
    "Lanceur",
    "Pugiliste brutal",
    "Sauvage enragé",
    "Superstitieux",
    "Terreur des mers",
    "Véritable primitif",
    "Archéologue",
    "Archiviste",
    "Artiste des rues",
    "Barde de cour",
    "Barde funèbre",
    "Casse cou",
    "Célébrité",
    "Chantemer",
    "Danseur des flammes",
    "Démagogue",
    "Derviche",
    "Détective",
    "Duelliste des arcanes",
    "Frappeson",
    "Geisha",
    "Le Marchand de sable",
    "Marionnettiste des ombres",
    "Orateur animal",
    "Prestidigitateur",
    "Scalde sauvage",
    "Soignechant",
    "Voix de la nature",
    "Arpenteur de monde",
    "Chuchoteur sauvage",
    "Croc de la nature",
    "Druide aquatique",
    "Druide arctique",
    "Druide de la jungle",
    "Druide des cavernes",
    "Druide des déserts",
    "Druide des marais",
    "Druide des montagnes",
    "Druide des plaines",
    "Druide des tempêtes",
    "Druide urbain",
    "Druide réincarné",
    "Enfant de la lune",
    "Flétrisseur",
    "Métamorphe sauvage",
    "Sage des menhirs",
    "Seigneur de la meute",
    "Bagarreur étrange",
    "Mage bâtard",
    "Sang sauvage",
    "Arbalétrier",
    "Archer",
    "Castagneur",
    "Combattant à deux armes",
    "Combattant à deux mains",
    "Combattant de la main libre",
    "Dragon",
    "Frappe tonnerre",
    "Gardien occulte",
    "Gladiateur",
    "Guerrier désarmé",
    "Guerrier mobile",
    "Guerrier mutagénique",
    "Guerrier sauvage",
    "Invincible",
    "Maître d'armes",
    "Maître d'hast",
    "Maître des armures",
    "Maître du bouclier",
    "Maître martial",
    "Malotru",
    "Monteur de bêtes",
    "Phalange",
    "Spécialiste du pavois",
    "Tacticien",
    "Chuchoteur spirituel",
    "Mage de siège",
    "Magicien exploiteur",
    "Maître des parchemins",
    "Poseur de bombes",
    "Sage ésotérique",
    "Sortiléro",
    "Adepte des armes",
    "Archer zen",
    "Artiste martial",
    "Chat sauvage",
    "Maître des écoles",
    "Maître des katas",
    "Maître des manoeuvres",
    "Maître ivre",
    "Moine de la main qui guérit",
    "Moine de la main vide",
    "Moine de la montagne sacrée",
    "Moine des quatre vents",
    "Moine du fantôme affamé",
    "Moine du lotus",
    "Moine fluide",
    "Moine qinggong",
    "Mystique ki",
    "Sensei",
    "Sohei",
    "tetori",
    "Bouclier béni",
    "Sorcière aux toxines",
    "Champion du temple",
    "Chevalier empyréen",
    "Chevalier étincelant",
    "Défenseur divin",
    "Élu",
    "Fléau des morts vivants",
    "Guerrier de la lumière sainte",
    "Guide saint",
    "Hospitalier",
    "Paladin assermenté",
    "Saint pistolet",
    "Saint tacticien",
    "Serviteur sacré",
    "Chevalier du sépulcre",
    "Évangéliste",
    "Guérisseur miséricordieux",
    "Prêtre cloîtré",
    "Saint combattant",
    "Seigneur des morts vivants",
    "Séparatiste",
    "Stratège divin",
    "Théologien",
    "Théurge ecclésiastique",
    "Arpenteur des profondeurs",
    "Champion rebelle",
    "Changeforme",
    "Chasseur de trophées",
    "Éclaireur de l'armée",
    "Fauconnier",
    "Gardien",
    "Guide",
    "Maître des bêtes",
    "Pisteur divin",
    "Rôdeur infiltré",
    "Rôdeur spirituel",
    "Rôdeur urbain",
    "Seigneur des chevaux",
    "Tirailleur",
    "Traqueur sauvage",
    "Trappeur",
    "Acrobate",
    "Bandit",
    "Bretteur",
    "Cambrioleur",
    "Caméléon",
    "Charlatan",
    "Chimiste clandestin",
    "Cocher",
    "Coriace",
    "Coureur des toits",
    "Éclaireur",
    "Effronté",
    "Empoisonneur",
    "Enquêteur",
    "Espion",
    "Fabricant de pièges",
    "Happe bourse",
    "Mage charlatan",
    "Maître des couteaux",
    "Pirate",
    "Roublard sanctifié",
    "Voyou",
    "Ninja",
    "Alchimiste des marais",
    "Alchimiste interne",
    "Animorphe",
    "Artificier des profondeurs",
    "Brasseur d'épines",
    "Chimiste enragé",
    "Chimiste inspiré",
    "Chimiste spirituel",
    "Chirurgien",
    "Collectionneur",
    "Homonculiste",
    "Maître des clones",
    "Maraudeur ailé",
    "Porte peste",
    "Psychonaute",
    "Pyrobombardier",
    "Réanimateur",
    "Saboteur",
    "Vivisectioniste",
    "Appât",
    "Cavalier des bêtes",
    "Champion audacieux",
    "Émissaire",
    "Garde d'honneur",
    "Hussard",
    "Porte étendard",
    "Stratège",
    "Lame sainte",
    "Évolutionniste",
    "Invocateur d'esprit",
    "Maître des couvées",
    "Maître invocateur",
    "Naturaliste",
    "Synthétiseur",
    "Synergiste",
    "Brise sortilège",
    "Chasseur de sorcières",
    "Exorciste",
    "Exterminateur sacré",
    "Hérétique",
    "Iconoclaste",
    "Infiltrateur",
    "Mangeur de pêchés",
    "Maître chasseur sacré",
    "Prêcheur",
    "Chercheur psychique",
    "Combattant intuitif",
    "Guide spirituel",
    "Oracle doublement maudit",
    "Oracle des étoiles",
    "Oracle planaire",
    "Oracle possédé",
    "Philosophe éclairé",
    "Prophète",
    "Amie des animaux",
    "Canalisatrice de maléfices",
    "Marchetombe",
    "Sorcière des mers",
    "Sorcière de village",
    "Sorcière des montagnes",
    "Forgeâme",
    "Kensai",
    "Lamelié",
    "Lamesort",
    "Lanceur de maléfices",
    "Myrmidarque",
    "Rejeton étrange",
    "Skirnir",
    "Spécialiste du bâton",
    "Arbalétrier d'élite",
    "Armure pistolet",
    "Maître du mousquet",
    "Mystérieux voyageur",
    "Pistolero",
    "Adepte des lames",
    "Agent étrange",
    "Arcaniste du sang",
    "Arcaniste illétré",
    "Mage blanc",
    "Maître élémentaire",
    "Occultiste",
    "Savant d'une école de magie",
    "Spécialiste des sortilèges",
    "Transmutateur à fourrure brune",
    "Bretteur inspiré",
    "Infiltré audacieux",
    "Lame volante",
    "Mousquetaire",
    "Mystérieux vengeur",
    "Petit bretteur",
    "Picaro",
    "Animiste",
    "Chaman non assermenté",
    "Chamanes animaux",
    "Chaman possédé",
    "Gardien spirituel",
    "Guérisseur",
    "Locuteur du passé",
    "Visionnaire",
    "Adepte de la vermine",
    "Chasseur au compagnon primitif",
    "Chasseur divin",
    "Chasseur sauvage",
    "Chef de meute",
    "Conspirateur",
    "Empiriste",
    "Enquêteur infiltré",
    "Harceleur d'acier",
    "Limier",
    "Spiritualiste",
    "Broyeur de métal",
    "Champion du bouclier",
    "Enfant sauvage",
    "Étrangleur",
    "Exemplaire",
    "Lutteur mutagénique",
    "Lutteur serpentin",
    "Champion de la Foi",
    "Chef de culte",
    "Commandant divin",
    "Désenchanteur",
    "Poing sacré",
    "Prêtre forgeron",
    "Cavalier sanguin",
    "Dévoreur de sorts",
    "Intermédiaire sanguin",
    "Métamorphe sanguin",
    "Primitif",
    "Sangacier",
    "Sanguin au sang mêlé",
    "Sang mêlé",
    "Sanguin intouchable",
    "Sanguin métamagique",
    "Sanguin verdoyant",
    "Champion prédestiné",
    "Destructeur de sorts",
    "Héraut du cor",
    "Scalde totémique",
    "Chasseur de primes",
    "Coupe jarret",
    "Gardien des tombes",
    "Libérateur",
    "Nettoyeur",
    "Tireur embusqué",
    "Tueur en première ligne",
    "Tueur stygien",
    "Âme invincible",
    "Annihilateur élémentaire",
    "Ascète élémentaire",
    "Chirurgien cinétique",
    "Cinétiste du sang",
    "Casse cou humiliant",
    "Maître du culte",
    "Marcheur spirituel",
    "Toxicologue",
    "Canalisateur de reliques",
    "Conteur",
    "Danseur spirituel",
    "Médium des kamis",
    "Médium réanimé",
    "Dévoreur de livres",
    "Hôte de guerre",
    "Nécroccultiste",
    "Shair",
    "Adepte informe",
    "Amnésique",
    "Duelliste psychique",
    "Esprit muté",
    "Canalisateur de geist",
    "Ectoplasmiste",
    "Esprit fracturé",
    "Onmyoji",
    "Spirite hanté",
    "Boucanier",
    "Derviche de l'aube",
    "Diva",
    "Druide des ouragans",
    "Ensorceleur tatoué",
    "Faux prêtre",
    "Corsaire",
    "Mage des ombres",
    "Primordialiste",
    "Épée du courage",
    "Pèlerin nomade",
    "Prêtre clandestin",
    "Prêtre croisé",
    "Flibustier",
    "Rôdeur libre des forêts",
    "Contrebandier",
    "Chercheur visionnaire",
    "Explorateur de cryptes",
    "Conjurateur féerique",
    "Chasseur de vampire",
    "Oracle au sang noir",
    "Sorcière de l'hiver",
    "Défenseur de la tour"
]

class_names = ["Barbare",
               "Barde",
               "Druide",
               "Ensorceleur",
               "Guerrier",
               "Magicien",
               "Moine",
               "Paladin",
               "Prêtre",
               "Rôdeur",
               "Roublard",
               "Alchimiste",
               "Antipaladin",
               "Chevalier",
               "Conjurateur",
               "Inquisiteur",
               "Oracle",
               "Sorcière",
               "Magus",
               "Ninja",
               "Pistolier",
               "Samouraï",
               "Arcaniste",
               "Bretteur",
               "Chaman",
               "Chasseur",
               "Enquêteur",
               "Lutteur",
               "Prêtre combattant",
               "Sanguin",
               "Scalde",
               "Tueur",
               "Cinétiste",
               "Hypnotiseur",
               "Médium",
               "Occultiste",
               "Psychiste",
               "Spirite",
               "Archer mage",
               "Arpenteur d'horizon",
               "Assassin",
               "Champion occultiste",
               "Chroniqueur",
               "Disciple draconien",
               "Duelliste",
               "Fidèle défenseur",
               "Gardien de la nature",
               "Gardien du savoir",
               "Héraut",
               "Maître chimiste",
               "Maître des ombres",
               "Maître espion",
               "Mystificateur profane",
               "Prophète enragé",
               "Théurge mystique",
               "Vengeur sacré"]

competence_names = ["Acrobaties",
                    "Art de la magie",
                    "Artisanat",
                    "Bluff",
                    "Connaissances (exploration souterraine)",
                    "Connaissances (folklore local)",
                    "Connaissances (géographie)",
                    "Connaissances (histoire)",
                    "Connaissances (ingénierie)",
                    "Connaissances (mystères)",
                    "Connaissances (nature)",
                    "Connaissances (noblesse)",
                    "Connaissances (plans)",
                    "Connaissances (religion)",
                    "Déguisement",
                    "Diplomatie",
                    "Discrétion",
                    "Dressage",
                    "Équitation",
                    "Escalade",
                    "Escamotage",
                    "Estimation",
                    "Évasion",
                    "Intimidation",
                    "Linguistique",
                    "Natation",
                    "Perception",
                    "Premiers secours",
                    "Profession",
                    "Psychologie",
                    "Représentation",
                    "Sabotage",
                    "Survie",
                    "Utilisation d'objets magiques",
                    "Vol"]


# TODO refractor this function to a single function that take an array an transform it back to an array of match
def verify_archetype(text: str):
    #TODO fix on the website on https://www.pathfinder-fr.org/Wiki/Pathfinder-RPG.Les%20arch%C3%A9types%20de%20classes.ashx
    #TODO The title for the link Maitre Invocateur is called Maitre Conjurateur
    #FIX MAITRE INVOCATEUR
    if text == "Maître Conjurateur":
        text = "Maitre Invocateur"
    #ENDFIX MAITRE INVOCATEUR

    archetypes = []
    lower_text = text.lower().replace("-", " ")
    lower_text = unidecode.unidecode(lower_text)
    for archetype_name in archetype_names:
        if unidecode.unidecode(archetype_name.lower()) == lower_text:
            archetypes.append(archetype_name)
    return archetypes


def verify_class(text: str):
    lower_text = text.lower()
    for class_name in class_names:
        if class_name.lower() in lower_text:
            return class_name
    return None


def verify_competence(text: str):
    competences = []
    lower_text = text.lower()
    for competence_name in competence_names:
        if competence_name.lower() in lower_text:
            competences.append(competence_name)
    return competences
