class_names = ["Barbare",
               "Barde",
               "Druide",
               "Ensorceleur",
               "Guerrier",
               "Magicien",
               "Moine",
               "Paladin",
               "Prêtre",
               "Rôdeur",
               "Roublard",
               "Alchimiste",
               "Antipaladin",
               "Chevalier",
               "Conjurateur",
               "Inquisiteur",
               "Oracle",
               "Sorcière",
               "Magus",
               "Ninja",
               "Pistolier",
               "Samouraï",
               "Arcaniste",
               "Bretteur",
               "Chaman",
               "Chasseur",
               "Enquêteur",
               "Lutteur",
               "Prêtre combattant",
               "Sanguin",
               "Scalde",
               "Tueur",
               "Cinétiste",
               "Hypnotiseur",
               "Médium",
               "Occultiste",
               "Psychiste",
               "Spirite",
               "Archer-mage",
               "Arpenteur d'horizon",
               "Assassin",
               "Champion occultiste",
               "Chroniqueur",
               "Disciple draconien",
               "Duelliste",
               "Fidèle défenseur",
               "Gardien de la nature",
               "Gardien du savoir",
               "Héraut",
               "Maître chimiste",
               "Maître des ombres",
               "Maître espion",
               "Mystificateur profane",
               "Prophète enragé",
               "Théurge mystique",
               "Vengeur sacré"]

competence_names = ["Acrobaties",
                    "Art de la magie",
                    "Artisanat",
                    "Bluff",
                    "Connaissances (exploration souterraine)",
                    "Connaissances (folklore local)",
                    "Connaissances (géographie)",
                    "Connaissances (histoire)",
                    "Connaissances (ingénierie)",
                    "Connaissances (mystères)",
                    "Connaissances (nature)",
                    "Connaissances (noblesse)",
                    "Connaissances (plans)",
                    "Connaissances (religion)",
                    "Déguisement",
                    "Diplomatie",
                    "Discrétion",
                    "Dressage",
                    "Équitation",
                    "Escalade",
                    "Escamotage",
                    "Estimation",
                    "Évasion",
                    "Intimidation",
                    "Linguistique",
                    "Natation",
                    "Perception",
                    "Premiers secours",
                    "Profession",
                    "Psychologie",
                    "Représentation",
                    "Sabotage",
                    "Survie",
                    "Utilisation d'objets magiques",
                    "Vol"]


def verify_class(text: str):
    lower_text = text.lower()
    for class_name in class_names:
        if class_name.lower() in lower_text:
            return class_name
    return None


def verify_competence(text: str):
    competences = []
    lower_text = text.lower()
    for competence_name in competence_names:
        if competence_name.lower() in lower_text:
            competences.append(competence_name)
    return competences
